install:
    - go install github.com/xephonhq/tsdb-proxy/cmd/tsdb-proxy
    
test:
    - go test -v -cover ./pkg/...
    - go test -race ./pkg/...
scripts:
  # fast test
  ft: go test ./pkg/...
  f:
    - gofmt -d -l -w ./pkg
  format: 
    - gofmt -d -l -w ./pkg
    - git status
