install:
    - go install github.com/xephonhq/xephon-b/cmd/xephon
test:
    - go test -v -cover ./pkg/...
    - go test -race ./pkg/...
    # - sh -c "go test -v -cover $(glide novendor)"
scripts:
  ft: go test ./pkg/...
  sm: go test -v ./pkg/simulator -run TestMachineSimulator